security:
  basic:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://54.37.20.87:5432/jade
    username: jadmin
    password: jetdev2018!
    driver-class-name: org.postgresql.Driver

mybatis:
  typeAliasesPackage: fr.jetdev.jade.models
  mapperLocations: classpath*:**/mappers/*.xml

logging:
  level:
    org.springframework.boot: DEBUG
    fr.jetdev.jade.repositories.ActivityReportDao: DEBUG
