security:
  basic:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jade
    username: postgres
    password: jetdev
    driver-class-name: org.postgresql.Driver

mybatis:
  typeAliasesPackage: fr.jetdev.jade.models
  mapperLocations: classpath*:**/mappers/*.xml

logging:
  level:
    org.springframework.boot: DEBUG
    fr.jetdev.jade.repositories.ActivityReportDao: DEBUG